### ISSUE TITLE
Test doesn't always exit cleanly

### ISSUE THREAD

**Issue by bryfox** [complexdatacollective/integration-tests#1]
From what I could tell in the logs:
- Selenium loses the connection and can't stop the app
  - App has already stopped?
- Jest sees open resources, and issues a warning instead of exiting

This happens in teardown after the tests complete. I don't think it indicates a problem with app behavior, but will need to research more.

Jest can be run with `--forceExit` as a workaround, but this is expected to be run by developers locally for now (not on CI).

**Comment by jthrilly** [comment]
Closing as obsolete
